version: "3"

services:
    nghed-mongo:
        build:
            context: ./mongo
            args:
                USER_ID: ${UID}
                GROUP_ID: ${GID}
        container_name: nghed-mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - ./mongo/data:/data/db
    nghed-node:
        build:
            context: ./node
            args:
                USER_ID: ${UID}
                GROUP_ID: ${GID}
        user: ${UID}:${GID}
        container_name: nghed-node
        depends_on:
            - nghed-mongo
        environment:
            - REPOSITORY=${CODE_REPOSITORY}
            - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@nghed-mongo:27017/${MONGO_DB}
            - SENTRY_DSN=${SENTRY_DSN}
        volumes:
            - ${SSH_KEY}:/home/node/.ssh/id_rsa:ro
#            - ~/.gitconfig:/home/node/.gitconfig:ro

networks:
    default:
        external:
            name: nghed-network
